---
ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35346166363136313037616633656466323636313935303637643431646534346263666264646162
  3034393766393036343437653036653130643633366330610a666466663138633738323166636337
  30303863616463356464376638303261633261653030616330333332643736343866613165313564
  6130663931366162660a636632303864363739323631303863373464613737633933386164636233
  6234
