---
- name: "systemd:systemd|daemon-reexec"
  ansible.builtin.systemd:
    daemon_reexec: true

- name: "systemd:journald|restart"
  ansible.builtin.service:
    name: "systemd-journald"
    state: "restarted"

- name: "systemd:resolved|restart"
  ansible.builtin.service:
    name: "systemd-resolved"
    enabled: true
    state: "restarted"

- name: "systemd:cron|restart"
  ansible.builtin.service:
    name: "cron.target"
    enabled: true
    state: "restarted"

- name: "systemd:oomd|restart"
  ansible.builtin.service:
    name: "systemd-oomd"
    enabled: true
    state: "restarted"
