---
msmtp_from_domain: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37643965626538333331336662666634366661363533613337633437346166383765323631663435
  6361363337383664613935383339666632613066626338660a323330376333373862303937383162
  30343134303131326239623066663732333066353133363936383764303565353863656234643538
  3862336264363137660a633066386662353061663037326164353138363737663162643334643966
  6431

msmtp_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61333832336337333130653464653836616366613238626464626538373063316237323732646161
  3236383632646263343932343431376236616332626163370a343663393031623036326132336132
  66353934353265656163306232633431623965653130376261393766626665653230383838316331
  6433626562303534610a666261633134326234386563656538306363633838306265336561373536
  33323863326239376238373339343066393666336463643962626263613731366465

msmtp_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36663063643232303836363935313634633965316433356535623961653035623734643034343562
  3761316565333962663562313131313233633133306238650a393431336462663433326166333232
  34343334346333643335353261363763363930363035633165363436373330393766373766326634
  6431396632353462380a356134366166323032633866303130313633626663373264373665323139
  63346364343866323839653839386266373135363138356361636666373132303562636564306435
  6261613665313462613233373139613735613339626431623335
