---
ansible_ssh_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65623638376464396530396466393265383132376630613966356138323361656462643636383238
  6365363032353532396563373536303539393436346430320a326162346466343035653562306333
  33383166613838623665333030626233643630623864363366613966353034396639336433663864
  3765386461323838640a393231636465396138646165633733626532663966393439383930366265
  6332
