---
apt_unattended_upgrades_origins:
  - "origin=Debian,codename=${distro_codename}-updates"
  - "origin=Tailscale,codename=${distro_codename},label=Tailscale"
  - "origin=apt.postgresql.org,codename=${distro_codename}-pgdg"
  - "origin=cloudsmith/caddy/stable,codename=${distro_codename}"
  - "origin=Proxmox,codename=${distro_codename},label=Proxmox Debian Repository"
