---
apt_unattended_upgrades_origins:
  - "o=Debian,n=${distro_codename}-updates"
  - "o=apt.postgresql.org,n=${distro_codename}-pgdg"
  - "o=cloudsmith/caddy/stable,n=${distro_codename}"
  - "o=Proxmox,n=${distro_codename},l=Proxmox Debian Repository,c=pve-no-subscription"
