---
ansible_become: true
ansible_python_interpreter: "/usr/bin/python3"
ansible_user: "root"

systemd_journald_retention_sec: "7d"
systemd_journald_system_max_use: "512M"

msmtp_host: "email-smtp.eu-north-1.amazonaws.com"

needrestart_overrides:
  ^systemd-(udevd|networkd|resolved|logind|journald): 0
  ^(docker|containerd): 0
  ^postgresql: 0
  ^(mysql|mariadb): 0
  ^caddy: 0
  ^mosquitto: 0
  ^zigbee2mqtt: 0
  ^tailscaled: 0
  ^dnsmasq: 0
  ^unbound: 0
  ^stubby: 0
  ^firewalld: 0
  ^polkit: 0
  ^dbus: 0
  ^networking: 0

sysctl_vars:
  - name: "net.core.rmem_max"
    value: 7500000

  - name: "net.core.wmem_max"
    value: 7500000

  - name: "vm.swappiness"
    value: 180

  - name: "vm.watermark_boost_factor"
    value: 0

  - name: "vm.watermark_scale_factor"
    value: 125

  - name: "vm.page-cluster"
    value: 0

zram_devices:
  zram0:
    zram-size: "ram / 2"
    compression-algorithm: "zstd"
