---
msmtp_from_addr: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36643336633736643936316163393038346139623764316337633432633833613238346238303466
  3366653137653434633630383030353237616538663766640a663432393234356463656339633965
  64316634303033336439633065663633333232393663363062316466386234653962383432316663
  3632623165393263390a363536656138353866343034316434326366393832363065396462653361
  63626365373336613433396461653038653430383033613731383237306334343136

msmtp_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  66333965393139373766303463656266313537306136373864373165613563643838643465616336
  3638653637373664616333386231383965393037363436610a326232663362323931656232343032
  31353633396238386166376663633663663232613234313330313162373438346435643033373431
  6661653130316631340a356133363830653531386431303538643561386137336136623866373962
  32626662346562343464346561613366623065663931343131393133353961313737

msmtp_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64336265346438366238613134666264663237383638383836623238333237336130373636666264
  3563643432336665336562326130643032306663666435640a313334313137316137303265613663
  30356366343234656266333834313332376131346661323032393833633139366231396363326638
  3466623937626562630a373239616530643664316161363561663530336435303230653532313738
  32613733333662333161393361346464376634616564663661353637356461653436616330656630
  3736643064303331663532353935393836396661346535313761
