---
ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63666465623137373961313232636231366162633133396637376538343730333137623432316465
  3234363038333834623439626530653038323939333438370a633933653662303838306339346331
  64623066313438643161633862623363346533303231613430386330653936656437366465353161
  3231356364306233390a633434373232383463373865353965323932326532316538393639366437
  38646666336531396135363436363039393036323561666634336537363634303234323862646562
  33383331626438366333393938623937343133656539366666663032633464626638663239336166
  65653232303330376131366538373434653965626233663662663161303135313263386439316564
  31636462363534666136
