---
ansible_become_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37316665626162653862666562323863663265323161306538386436303666303033646438626531
  3332616130383633323762343361333137613034393966650a626338643131363835346161303733
  36323366356664663630396264303563373135393230383531653565366438623361343762326338
  3166323965333062310a316361396565356235323038616564623936306638353763353265663761
  66323466313233663165363737643332353439356532383462383531313537303334326133666532
  3938343233303333306437396635653631336463613330663339
