---
- name: "apt-unattended-upgrades:install_packages"
  ansible.builtin.package:
    name:
      - "unattended-upgrades"
      - "apt-listchanges"

- name: "apt-unattended-upgrades:configure"
  ansible.builtin.template:
    src: "52unattended-upgrades-local.j2"
    dest: "/etc/apt/apt.conf.d/52unattended-upgrades-local"
    mode: "0640"

- name: "apt-unattended-upgrades:listchanges:configure"
  ansible.builtin.template:
    src: "listchanges.conf.j2"
    dest: "/etc/apt/listchanges.conf"
    mode: "0640"
