---
- name: "tgsend:configure"
  ansible.builtin.template:
    src: "telegram-send.conf.j2"
    dest: "/etc/telegram-send.conf"
    owner: "root"
    group: "root"
    mode: "0640"
  when:
    - "tgsend_bot_token | length > 0"
    - "tgsend_chat_id | length > 0"
  notify: "tgsend|test"
