---
msmtp_from_addr: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30303130613333656132323330396432346630653638323263366430623961653130643562666236
  6564303264666338336333353538386638336431343463380a383137353462363037353464313464
  31626265373839363231383930623333653330636436643465623032346334653634326562633130
  6536333961353630630a663233613137303837313262343139663139366435316633643631633163
  62373138666230316530633634323534383432346530313861373236333462333735

msmtp_user: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65643266663563353530343338666333386164616662636131333138323836656531316364653936
  6563613037653239336363356263656530306630303762380a376330336131376134613331343938
  30353237666232383633306235313062626366323765316530663131373137633039366662646234
  3830353537313838660a643934326332356466643230373135383862393631636130633230623932
  33393862636236373634613734666463303435343531383335303634383262313266

msmtp_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37656439316536306234356337336536306438303238376662646538663730333761323233623135
  6464663632373636336639646339353864383766623561370a373336316133653933633061376332
  64626161646136303863376261323837626531353365343831303034396436346335376661613432
  3537326561373835650a303139316231663536663636623437666233306339643031363865333561
  64306661626432366363376134383936376261333430386163623338666235393062373338353337
  3335353765643236396566363437306131323430343561653238
